language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - ~/.gradle/wrapper
    - ~/.gradle/caches

before_install:
  - cd springbootsample
  - chmod +x gradlew


deploy:
  provider: releases
  api_key: 3119c754dd5f6826240b0172379ee36c9b1f2b78
  file: build/libs/springbootsample-1.0-SNAPSHOT.war
  skip_cleanup: true
  on:
    tags: true